### ISSUE TITLE
Add: Default values for working hours and days

### ISSUE THREAD

**Issue by cadesalaberry** [DwarfNet/The-End-of-Sprint-Project#2]
Defaults to 7h per day with Monday to Friday working days.

![screenshot from 2017-04-24 10-03-48](https://cloud.githubusercontent.com/assets/1447513/25327683/60a4164e-28d5-11e7-8815-be4b6c9a7fc2.png)

**Comment by DwarfNet** [comment]
tu as testé avec quel navigateur parce que j ai pas ce probleme de mon coté.

**Comment by cadesalaberry** [comment]
I think it is because there is no "New user" line in the table.

Once you click on a user, the default values just go away, and there is no way to have them again (apart from refreshing the page).

**Comment by DwarfNet** [comment]
Solved. with a reload.
