### ISSUE TITLE
Del: Github ID

### ISSUE THREAD

**Issue by cadesalaberry** [DwarfNet/The-End-of-Sprint-Project#3]
If the Github ID adds no feature, it should be removed.

**Comment by DwarfNet** [comment]
il permet de differencier les dev. c est plus unique qu un prenom seul. apres je peux mettre un prenom / nom a la place de nom/id

**Comment by cadesalaberry** [comment]
Then I guess trying to minimise the number of inputs, just a github id should be enough.

**Comment by DwarfNet** [comment]
Solved.
