### ISSUE TITLE
Mod: Unify your buttons

### ISSUE THREAD

**Issue by cadesalaberry** [DwarfNet/The-End-of-Sprint-Project#5]
![screenshot from 2017-04-24 10-12-03](https://cloud.githubusercontent.com/assets/1447513/25328013/89a4f4d6-28d6-11e7-8047-f70958b0d224.png)
![screenshot from 2017-04-24 10-11-54](https://cloud.githubusercontent.com/assets/1447513/25328014/89a56c90-28d6-11e7-9f81-b263fdc61844.png)
![screenshot from 2017-04-24 10-11-48](https://cloud.githubusercontent.com/assets/1447513/25328012/89a2f816-28d6-11e7-9b09-b88a9b41f657.png)

**Comment by DwarfNet** [comment]
Solved.
